---
title: "FGEM GO Analysis"
author: "Nicholas Knoblauch"
date: "October 20, 2015"
output: html_document
---

#Overview

The GO analysis consisted of analyzing Bayes Factors for 18735 genes and 5906 GO terms.  Each GO term had at least 4 genes, and each gene had at minimum 0 GO terms (that's bad), and at most 148 go terms, with an average of 8.387.

The results 

```{r}
library(plyr)
library(Matrix)
setwd("~/Dropbox/BayesianDA/FGEM/Data/FGEM_GO_RDS/")

BFile <- "../TADA_ASC_SSC_results_Dec23.csv"
BF.G <- read.table(BFile,header=T,sep=",")
B <- BF.G$BF

GOmat <- readRDS("../GOmat.RDS")
GOres.files <- dir()
GOres <- ldply(GOres.files,readRDS)
FGEM.df$p <- pchisq(FGEM.df$Chisq,df = 1,lower.tail = F)
GOres$pval <- pchisq(GOres$Chisq,df=1,lower.tail=F)
GOres <- GOres[order(GOres$pval),]
GOres$adjp <- p.adjust(GOres$pval,method = "fdr")
head(GOres[order(abs(GOres$Beta),decreasing = T),])

sigGOres <- GOres[GOres$pval<0.05,]
sigGOres <- sigGOres[order(abs(sigGOres$Beta),decreasing = T),]
x <- numeric(length(B))

Beta <- coefficients(glm(Z~x,family=binomial))
pvec <- 1/(1+exp(-(Beta[1]+Beta[2]*x)))

uvec  <- (pvec*B)/((pvec*B)+(1-pvec))
      #This is where we optimize the Q function (in this case, using logistic regression)
      Beta[,i] <- coefficients(glm(uvec~x,family=quasibinomial(link="logit")))
      pvec  <- 1/(1+exp(-(Beta[1,i]+Beta[2,i]*x)))
coefficients(glm(B~x,family=quasibinomial(link="logit")))



```


We can plot some of the probablilities for the highest significant Betas vs the probabilities under the null


```{r}

nGOmat <- GOmat[,sigGOres$X1]
nnGOmat <- nGOmat[,colSums(nGOmat)>100]
rownames(sigGOres) <- sigGOres$X1

nB <- glm(B~nnGOmat,family=quasibinomial(link="logit"))
for(i in 1:6){
  gt <- colnames(nnGOmat)[i]
  Beta <- c(sigGOres[gt,"Intercept"],sigGOres[gt,"Beta"])
  x <- GOmat[,gt]
  upp <- 1/(1+exp(-(Beta[1]+Beta[2]*x)))
  plot(upp~B,main=paste(gt,sum(x)))
}


```

reranking of genes

