library(readr)
require(reshape2)
require(topGO)
library(dplyr)
datalink <- "https://www.dropbox.com/s/7k62nly5jzj2j00/TADA_ASC_SSC_results_Dec23.csv?dl=1"
datadf <- read_delim(datalink,delim=",",col_names=T)
genes <- unique(datadf$Gene)
mdf <- melt(topGO::annFUN.org("BP",feasibleGenes=genes,mapping="org.Hs.eg.db",ID="symbol"))
mdf <- dplyr::as_data_frame(mdf)
BPGOdf <- dplyr::select(mdf,Gene=value,feature=L1) %>% dplyr::mutate(value=1,class="GO_BP")
save(BPGOdf,file="data/BP_GO.rdata")
