// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP FGEM_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// FGEM_Logit_log_lik_cpp
NumericVector FGEM_Logit_log_lik_cpp(const arma::vec& Beta, const arma::mat& x, const arma::vec B);
RcppExport SEXP FGEM_FGEM_Logit_log_lik_cpp(SEXP BetaSEXP, SEXP xSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(FGEM_Logit_log_lik_cpp(Beta, x, B));
    return rcpp_result_gen;
END_RCPP
}
