// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fgem.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fgem_grad_stan
Eigen::ArrayXd fgem_grad_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool log_BF);
RcppExport SEXP _fgem_fgem_grad_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(fgem_grad_stan(par, X, BF, l2, l1, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// sp_fgem_grad_stan
Eigen::ArrayXd sp_fgem_grad_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::SparseMatrix<double>> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool log_BF);
RcppExport SEXP _fgem_sp_fgem_grad_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_fgem_grad_stan(par, X, BF, l2, l1, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// sp_fgem_hess_stan
Eigen::MatrixXd sp_fgem_hess_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::SparseMatrix<double>> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool neg, const bool log_BF);
RcppExport SEXP _fgem_sp_fgem_hess_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP negSEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type neg(negSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_fgem_hess_stan(par, X, BF, l2, l1, neg, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// fgem_hess_stan
Eigen::MatrixXd fgem_hess_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool log_BF);
RcppExport SEXP _fgem_fgem_hess_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(fgem_hess_stan(par, X, BF, l2, l1, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// sp_fgem_lik_stan
double sp_fgem_lik_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::SparseMatrix<double>> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool log_BF);
RcppExport SEXP _fgem_sp_fgem_lik_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_fgem_lik_stan(par, X, BF, l2, l1, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// l1_norm_penalty
double l1_norm_penalty(Eigen::Map<Eigen::ArrayXd> par, const double l1);
RcppExport SEXP _fgem_l1_norm_penalty(SEXP parSEXP, SEXP l1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    rcpp_result_gen = Rcpp::wrap(l1_norm_penalty(par, l1));
    return rcpp_result_gen;
END_RCPP
}
// l2_norm_penalty
double l2_norm_penalty(Eigen::Map<Eigen::ArrayXd> par, const double l2);
RcppExport SEXP _fgem_l2_norm_penalty(SEXP parSEXP, SEXP l2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    rcpp_result_gen = Rcpp::wrap(l2_norm_penalty(par, l2));
    return rcpp_result_gen;
END_RCPP
}
// fgem_lik_stan
double fgem_lik_stan(const Eigen::Map<Eigen::ArrayXd> par, const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::ArrayXd> BF, const double l2, const double l1, const bool log_BF);
RcppExport SEXP _fgem_fgem_lik_stan(SEXP parSEXP, SEXP XSEXP, SEXP BFSEXP, SEXP l2SEXP, SEXP l1SEXP, SEXP log_BFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd> >::type BF(BFSEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const bool >::type log_BF(log_BFSEXP);
    rcpp_result_gen = Rcpp::wrap(fgem_lik_stan(par, X, BF, l2, l1, log_BF));
    return rcpp_result_gen;
END_RCPP
}
// make_env_obj
Rcpp::List make_env_obj(bool sparse, const bool log);
RcppExport SEXP _fgem_make_env_obj(SEXP sparseSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    Rcpp::traits::input_parameter< const bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(make_env_obj(sparse, log));
    return rcpp_result_gen;
END_RCPP
}
// log_1p_exp
Rcpp::NumericVector log_1p_exp(SEXP x);
RcppExport SEXP _fgem_log_1p_exp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log_1p_exp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fgem_fgem_grad_stan", (DL_FUNC) &_fgem_fgem_grad_stan, 6},
    {"_fgem_sp_fgem_grad_stan", (DL_FUNC) &_fgem_sp_fgem_grad_stan, 6},
    {"_fgem_sp_fgem_hess_stan", (DL_FUNC) &_fgem_sp_fgem_hess_stan, 7},
    {"_fgem_fgem_hess_stan", (DL_FUNC) &_fgem_fgem_hess_stan, 6},
    {"_fgem_sp_fgem_lik_stan", (DL_FUNC) &_fgem_sp_fgem_lik_stan, 6},
    {"_fgem_l1_norm_penalty", (DL_FUNC) &_fgem_l1_norm_penalty, 2},
    {"_fgem_l2_norm_penalty", (DL_FUNC) &_fgem_l2_norm_penalty, 2},
    {"_fgem_fgem_lik_stan", (DL_FUNC) &_fgem_fgem_lik_stan, 6},
    {"_fgem_make_env_obj", (DL_FUNC) &_fgem_make_env_obj, 2},
    {"_fgem_log_1p_exp", (DL_FUNC) &_fgem_log_1p_exp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fgem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
