# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient for FGEM likelihood
#' This is an attempt to use stan's AD features to optimize the FGEM likelihood
#' @export
fgem_grad_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, log_BF = FALSE) {
    .Call('_fgem_fgem_grad_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, log_BF)
}

#' Gradient for FGEM likelihood
#' This is an attempt to use stan's AD features to optimize the FGEM likelihood
#' @export
sp_fgem_grad_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, log_BF = FALSE) {
    .Call('_fgem_sp_fgem_grad_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, log_BF)
}

#' evd_dnorm_hess_stan
#'
#' This is an attempt to use stan's AD features to calculate a hessian
#' for the RSSp likelihood
#'
#' @export
sp_fgem_hess_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, neg = FALSE, log_BF = FALSE) {
    .Call('_fgem_sp_fgem_hess_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, neg, log_BF)
}

#' evd_dnorm_hess_stan
#'
#' This is an attempt to use stan's AD features to calculate a hessian
#' for the RSSp likelihood
#'
#' @export
fgem_hess_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, log_BF = FALSE) {
    .Call('_fgem_fgem_hess_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, log_BF)
}

#'
#' This is an attempt to use stan's AD features to calculate a gradient
#' for the FGEM likelihood
#'
#' @export
sp_fgem_lik_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, log_BF = FALSE) {
    .Call('_fgem_sp_fgem_lik_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, log_BF)
}

l1_norm_penalty <- function(par, l1) {
    .Call('_fgem_l1_norm_penalty', PACKAGE = 'fgem', par, l1)
}

l2_norm_penalty <- function(par, l2) {
    .Call('_fgem_l2_norm_penalty', PACKAGE = 'fgem', par, l2)
}

fgem_lik_stan <- function(par, X, BF, l2 = 0.0, l1 = 0.0, log_BF = FALSE) {
    .Call('_fgem_fgem_lik_stan', PACKAGE = 'fgem', par, X, BF, l2, l1, log_BF)
}

make_env_obj <- function(sparse = FALSE, log = FALSE) {
    .Call('_fgem_make_env_obj', PACKAGE = 'fgem', sparse, log)
}

log_1p_exp <- function(x) {
    .Call('_fgem_log_1p_exp', PACKAGE = 'fgem', x)
}

