# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient for FGEM likelihood
#' This is an attempt to use stan's AD features to optimize the FGEM likelihood
#' @export
fgem_grad_stan <- function(par, X, BF, prec = 0.0, neg = FALSE) {
    .Call('_fgem_fgem_grad_stan', PACKAGE = 'fgem', par, X, BF, prec, neg)
}

#' Gradient for FGEM likelihood
#' This is an attempt to use stan's AD features to optimize the FGEM likelihood
#' @export
sp_fgem_grad_stan <- function(par, X, BF, prec = 0.0, neg = FALSE) {
    .Call('_fgem_sp_fgem_grad_stan', PACKAGE = 'fgem', par, X, BF, prec, neg)
}

#'
#' This is an attempt to use stan's AD features to calculate a gradient
#' for the FGEM likelihood
#'
#' @export
sp_fgem_lik_stan <- function(par, X, BF, prec = 0.0, neg = FALSE) {
    .Call('_fgem_sp_fgem_lik_stan', PACKAGE = 'fgem', par, X, BF, prec, neg)
}

#' evd_dnorm_hess_stan
#' 
#' This is an attempt to use stan's AD features to calculate a hessian 
#' for the RSSp likelihood
#'
#' @export
fgem_hess_stan <- function(par, X, BF, prec = 0.0) {
    .Call('_fgem_fgem_hess_stan', PACKAGE = 'fgem', par, X, BF, prec)
}

#' fit fgem with bfgs
#'
#' fit fgem using c++ BFGS algorithm
#'
#' @export
fgem_fit_bfgs <- function(par, X, BF, prec = 0.0, epsilon = 1e-6, max_iter = 100L) {
    .Call('_fgem_fgem_fit_bfgs', PACKAGE = 'fgem', par, X, BF, prec, epsilon, max_iter)
}

#' fit every column of X with the BFGS algorithm
#'
#' fit fgem using c++ BFGS algorithm
#'
#' @export
marginal_fgem_fit_bfgs <- function(X, BF, prec = 0.0, epsilon = 1e-6, max_iter = 100L, progress = TRUE) {
    .Call('_fgem_marginal_fgem_fit_bfgs', PACKAGE = 'fgem', X, BF, prec, epsilon, max_iter, progress)
}

make_env_obj <- function(sparse = FALSE) {
    .Call('_fgem_make_env_obj', PACKAGE = 'fgem', sparse)
}

