# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('FGEM_timesTwo', PACKAGE = 'FGEM', x)
}

FGEM_Logit_log_lik_cpp <- function(Beta, x, B) {
    .Call('FGEM_FGEM_Logit_log_lik_cpp', PACKAGE = 'FGEM', Beta, x, B)
}

